#-------------------------------
# General Site Settings
baseURL = "https://esapir.github.io/"
languageCode = "en-us"
title = "Erik Sapir"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

  [[menu.main]]
    identifier = "elements"
    name = "Elements"
    url = "/elements"
    weight = 4


[params]
  description = "Erik Sapir's blog"
  logo = "/images/logo-no-background.svg"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Camelia Mendes"
    author__bio = "Designs, talks, and writes about web, ethics, privacy, and dev. I share design tutorials, free resources and inspiration."
    author__avatar = "https://via.placeholder.com/200x200"

  [[params.social]]
    icon = "logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/esapir"

  [[params.social]]
    icon = "logo-linkedin"
    name = "Linkedin"
    link = "https://www.linkedin.com/in/esapir/"

  [[params.social]]
    icon = "logo-medium"
    name = "Medium"
    link = "https://medium.com/@esapir"

  [[params.social]]
    icon = "calendar-number"
    name = "Calendly"
    link = "https://calendly.com/eriksapir/mentoring"


  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Welcome! I'm Erik Sapir"
    hero__description = "I am a technical leader and have been building complex system for the last two decades. I am passionate about engineering culture, startups, mentoring, coding and system architecture."
    hero__image = "/images/profile.jpg" 
# 
#   # Newsletter
#   [params.mailchimp]
#     mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#     mailchimp__input__text = "Your email goes here"
#     mailchimp__button__text = "Update me"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "esapir@gmail.com" # Add your email for contant form

    # NOTE
    # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = "demo-menca" # Add your shortname for Disqus Comment. For example demo-menca


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
